require("control.controls")
require("control.entities")
require("control.general")
require("control.gui")
require("control.inventory")
require("control.remote")
require("control.settings")
require("control.shortcuts")
